name: pull req

on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:

      - name: pull req
        env:
          pat: ${{ secrets.EXTERNAL_REPO_PAT }}
        run: |
          echo "cloning app repo"
          git clone https://momohsen2013:$pat@github.com/momohsen2013/project1.git
          pwd



        
