name: pull req

on:
  workflow_dispatch: 

jobs:
  
  get_release_name:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.EXTERNAL_REPO_PAT }}
          
      - name: Set up GitHub CLI
        run: |
          echo ${{ secrets.GH_TOKEN }} | gh auth login --with-token
        env:
          GH_TOKEN: ${{ secrets.EXTERNAL_REPO_PAT }}


        
