name: pull req

on:
  workflow_dispatch: 

jobs:
  
  get_release_name:
    runs-on: ubuntu-latest
    steps:

          


      - name: change go.mod using sed && pull req 
        run: |
          gh auth login --with-token ${{ secrets.EXTERNAL_REPO_PAT }}

        
