name: pull req

on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      - name: pull req
        env:
          pat: ${{ secrets.EXTERNAL_REPO_PAT }}
        run: |
          git config --global user.email "mohamed.mohsen@foodji.com"
          git config --global user.name "momohsen2013"
          git checkout -b test
          echo "6" > test.txt
          git add .
          git commit -m "test" test.txt
          git push --set-upstream origin test
          gh pr create --base main --head test --fill
 



        
