name: pull req

on:
  workflow_dispatch: 

jobs:
  
  get_release_name:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list
          sudo apt-get update
          sudo apt-get install gh
    
      - name: Debug
        run: |
          echo "GH_TOKEN: ${{ secrets.EXTERNAL_REPO_PAT }}"
          gh --version
          
      - name: Set up GitHub CLI
        run: |
          which gh
          gh repo list



        
