name: pull req

on:
  workflow_dispatch: 

jobs:
  
  get_release_name:
    runs-on: ubuntu-latest
    steps:

          


      - name: change go.mod using sed && pull req 
        env:
          GH_TOKEN: ${{ secrets.EXTERNAL_REPO_PAT }}
        run: |
          release_name=$(gh release list |head -1 |awk '{print $1}')
          echo  "$release_name"
          echo "cloning app repo"
          git clone https://momohsen2013:${{ secrets.EXTERNAL_REPO_PAT }}@github.com/momohsen2013/go_webapp.git

          git config --global user.email "mohamed.mohsen@foodji.com"
          git config --global user.name "momohsen2013"
          cd go_webapp
          git checkout -b fix_gomod_version
          sed -i 's|github.com/Foodji/common v[0-9].*.*|github.com/Foodji/common "$release_name" |' go.mod          
          git add .
          git commit  -m "chore: (updating webapp release version; no production code change)"  
          git push  --set-upstream origin fix_gomod_version --force
          gh pr create -B main -H fix_gomod_version --title 'Merge branch_to_merge into base_branch' --body "pull req"
      
     
 
          
