name: pull req

on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: pull req
        run: |
          echo "cloning app repo"
          git clone https://momohsen2013:${{ secrets.EXTERNAL_REPO_PAT }}@github.com/momohsen2013/project1.git
          pwd



        
