name: pull req

on:
  workflow_dispatch: 

jobs:
  
  get_release_name:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.EXTERNAL_REPO_PAT }}
          repository: momohsen2013/go_webapp
          ref: main
          


      - name: change go.mod using sed && pull req 
        run: |
          git config --global user.email "mohamed.mohsen@foodji.com"
          git config --global user.name "momohsen2013"
          release_name=${{ github.event.release.tag_name }}
          git checkout -b fix_gomod_version
          sed -i 's|github.com/Foodji/common v[0-9].*.*|github.com/Foodji/common $release_name|' go.mod


      
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: update authors
          title: Update AUTHORS
          body: Credit new contributors by updating AUTHORS
          branch: fix_gomod_version
          
