name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  # TEST
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Search for pattern in branch name and extract ticket number (FJI-XXXX)
        env:
         BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        id: pattern_search
        run: |
          echo "$BRANCH_NAME"
          ticket_number=$(echo  "$BRANCH_NAME" | grep -Eo 'FJI-\d+' || echo "")
    
          if [ -n "$ticket_number" ]; then
            echo "Ticket number found: $ticket_number"
          else
            echo "Ticket number not found."
          fi  
          echo "ticket_number=$ticket_number" >> "$GITHUB_OUTPUT"
